### ISSUE TITLE
Rename data-cube to vispy_viewer

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#10]
In order to make this into a plugin package (as described in #1) we need to rename the `data-cube` folder to be a name that can be a valid Python module, so I would like to suggest `vispy_viewer` for now.

@PennyQ - I didn't want to make the change since it might conflict with some changes you are already making, but when you have committed other changes, could you do this renaming?

**Comment by PennyQ** [comment]
Ok. I'll do it.

**Comment by ChrisBeaumont** [comment]
It might be worth keeping in mind that vispy could be used for more than 1 viewer, so `vispy_viewer` might be too generic?

**Comment by astrofrog** [comment]
What about simply calling it `vispy_plugin` and then it can be used for any vispy-related viewers?

**Comment by ChrisBeaumont** [comment]
Maybe `vispy_volume`?

**Comment by maxwelltsai** [comment]
Yes, vispy_volume sounds good.

**Comment by astrofrog** [comment]
Done in e3ff553567b721a8925106c0552169d51e9883f1
