### ISSUE TITLE
Linking Pixel Axis From 1D Array to Pixel Axis of 2D Array

### ISSUE THREAD

**Issue by dborncamp** [glue-viz/glue-vispy-viewers#101]
I am trying to link the Y axis of a 2 dimensional array (attached file: col100_sci.txt) to the index of a 1 dimensional array (attached file f100.txt). I was hoping that when I select something in the 1 dimensional file I could get the corresponding rows highlighted.

[f100.txt](https://github.com/glue-viz/glue-3d-viewer/files/198539/f100.txt)
[col100_sci.txt](https://github.com/glue-viz/glue-3d-viewer/files/198540/col100_sci.txt)

**Comment by PennyQ** [comment]
@dborncamp Could you tell us which data_loading method should be chose when opening these two datasets? Thanks!

**Comment by astrofrog** [comment]
(Just for some background this was an issue that happened at the tutorial today, will post more details to this issue)

**Comment by astrofrog** [comment]
(this issue really applies to glue core, not the 3d plugin repo)

**Comment by dborncamp** [comment]
@PennyQ This was read in using the `qglue` interface from ipython. The data originated from an open HDF5 file but it was casted to numpy arrays before opening.

@astrofrog Oops. Should I open another issue there?
