### ISSUE TITLE
Add back fov=60 to camera

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#102]
In the current 3D view, it's impossible to know which part of the cube is in front and which is behind now that the `fov=60` option has been removed.

I understand that this was removed to make the selection easier, but there should be a way to access this additional transformation from VisPy.

@PennyQ - can you clarify why exactly this option had to be removed?

**Comment by PennyQ** [comment]
@astrofrog The problems is that @maxwelltsai and I found there is a 'mismatch' between the 2D selection on screen and the 3D data points when `fov=60` is there. 

Our transform scheme `self.tr = self.scatter.node_transform(self.view)` is calculated from `view` to the `visual` and it seems the camera perspective setting is not included in it, which might be the reason for the mismatch problem.

**Comment by astrofrog** [comment]
Ok, I'll look into it to see if it can be fixed

**Comment by astrofrog** [comment]
This may be a VisPy bug - see the issue I opened here: https://github.com/vispy/vispy/issues/1198 - let's see what the VisPy developers find.

**Comment by astrofrog** [comment]
This turns out to not be a VisPy bug but see vispy/vispy#1198 for more details on how to get the correct coordinates.

**Comment by astrofrog** [comment]
@PennyQ @maxwelltsai - do you want to work on adding back the FOV now that we have a solution? Basically, the solution is that if you have a visual e.g. `scatter`, you can find the full transform with:

``` python
tr = scatter.get_transform(map_from='visual', map_to='canvas')
```

Then transform the coordinates with:

``` python
trpos = tr.map(pos)
```

and then renormalize the positions (see vispy issue above):

``` python
trpos /= trpos[:,3:]
```

Do you want to investigate whether this fixes it, and if so, open a pull request?

**Comment by PennyQ** [comment]
@astrofrog Yeah sure, I will check it

**Comment by astrofrog** [comment]
Done in #124 by @PennyQ - thanks!
