### ISSUE TITLE
min/max limitation setting of volume&scatter plots

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#118]
`min/max limitation setting` for both volume and scatter plots doesn't work correctly. The `Visual` outside the gridbox should not be shown.

![image](https://cloud.githubusercontent.com/assets/13411839/14582361/a25eb1a0-03d0-11e6-8220-093fcd258b7b.png)

**Comment by PennyQ** [comment]
We should `set_data(cutted_array)` to each visual on `_update_limits()` in `vispy_widget.py`, now there is only setting for the transform of each visual.

**Comment by astrofrog** [comment]
Right, it was actually intentional to leave the visual outside the box originally _but_ I think maybe it does make sense to hide stuff outside the box otherwise it can be confusing. The same applies for the scatter plots.

**Comment by astrofrog** [comment]
This is the same issue as https://github.com/glue-viz/glue-vispy-viewers/issues/175

**Comment by astrofrog** [comment]
Done in #203
