### ISSUE TITLE
Extract spectra line from different shape of selected region

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#141]
Extend the shape of spectra line extractor on `Image Viewer` from current 'rectangle' to more choices like 'free lasso'.

**Comment by PennyQ** [comment]
See the PR https://github.com/glue-viz/glue/pull/994

**Comment by astrofrog** [comment]
Done in https://github.com/glue-viz/glue/pull/994 - thanks @PennyQ!
