### ISSUE TITLE
Add data value dependent selection 

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#167]
Enable the 3D selection to 'filter' possible interesting regions depend on the data value.

One application for this is to select long and narrow structure within a 3D cube, which is hard to do with current selection options (including floodfill).

My thought is to add a checkbox on left panel that toggle the selection calculated upon array structure (what we do now) or data value, and use  the lowest value to be shown as white in volum as the threshold. @astrofrog Do you have any advice for this? :)

**Comment by astrofrog** [comment]
@PennyQ - could you clarify what you mean by 'calculated upon array structure or data value'? I thought the flood fill and contour selections were based on the data values in the array?

**Comment by PennyQ** [comment]
Oh I mean now our basic selection (rectangle, lasso etc.) are based on the data array shape, as `self.trans_ones_data = np.transpose(np.ones(layer.data.shape))` . So when we select one region we get the whole 3D region along eyesight. 

The value selection for them could be done through setting limits, while the limits setting doesn't work well now, I will open a new issue for it, thanks!
