### ISSUE TITLE
Pressing escape makes viewer disappear

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#188]
Instead it should just cancel the selection as for the 2D viewers

**Comment by PennyQ** [comment]
@astrofrog Good idea, is this like a shortcut for closing viewer window?

**Comment by astrofrog** [comment]
It shouldn't be - for the 2D viewers, when doing a selection, you can press escape to cancel the selection, but in the 3D viewers it is making the viewer go gray. Do you see this issue, and could you investigate?

**Comment by PennyQ** [comment]
Oh yeah I see it, sure I will have a look at it !

**Comment by astrofrog** [comment]
@PennyQ - thanks for the fix! Yes it would be nice if escape also cancelled the lasso selection

**Comment by astrofrog** [comment]
In any case, this issue was fixed in #193
