### ISSUE TITLE
A dramatic extension during floodfill selection in 3D volume viewer

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#189]
There is a dramatic extension of floodfill selection from 'no selection' to a large region, in 3D volume rendering viewer, while it seems work well in our standalone [script](https://github.com/glue-viz/glue-3d-selection/blob/master/floodfill_selection/volume_selection.py) 

I tried to change the threshold for extension but it doesn't help, so I guess the volume dataset also needs a 'normalization' based on value distribution, so the extension could be smoothed 

@astrofrog Do you have any ideas on this issue?

**Comment by astrofrog** [comment]
@PennyQ - can this be closed?

**Comment by PennyQ** [comment]
Yes and I will close it here ;)
