### ISSUE TITLE
Fix selections when multiple datasets are present

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#220]
In cases where there are e.g. multiple datasets in a 3D scatter plot or e.g markers in a volume rendering, we should make sure that selections are applied to all visible datasets.

**Comment by PennyQ** [comment]
there is a previous issue https://github.com/glue-viz/glue-vispy-viewers/issues/93 and some comments

**Comment by astrofrog** [comment]
Done in #208
