### ISSUE TITLE
Issue with Qt4 and macos Sierra

### ISSUE THREAD

**Issue by macrocosme** [glue-viz/glue-vispy-viewers#228]
Hi, 

I have recently noticed the following issue with the 3D scatter plot after upgrading to macos 10.12:  
```
 (...)
RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_FRAMEBUFFER_OPERATION
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x1252684d0>> for DrawEvent
ERROR: Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x1252684d0>> for DrawEvent
ERROR:vispy:Invoking <bound method SceneCanvas.on_draw of <SceneCanvas (PyQt4) at 0x1252684d0>> for DrawEvent
```
I think it's the same issue as the following one: https://github.com/vispy/vispy/issues/1290
I think that macos Sierra drivers and Qt4 aren't happy with each others...

**Comment by astrofrog** [comment]
I actually see that on 10.11 too, and saw it after upgrading laptops but keeping the OS the same, so I had thought it was to do with graphics cards, but I might be wrong. In any case, it should be possible to simply silence these errors since they are not of interest to the user.

**Comment by astrofrog** [comment]
@macrocosme - does the scatter plot still work though, or is the canvas empty?

**Comment by macrocosme** [comment]
@astrofrog The box is there, but without any content. 

I'm not sure what the cause is to be honnest. As you say, it may be related to the graphics card.

**Comment by astrofrog** [comment]
@macrocosme - ah I see, I will investigate!

**Comment by macrocosme** [comment]
@astrofrog - Sounds good to me!
