### ISSUE TITLE
Point selection on 3D scatter plot will pick a line of points 

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#231]
As below, click/point selection on the side of grid box will pick several points along a line, instead of pick ing one point

![image](https://cloud.githubusercontent.com/assets/13411839/20644170/ed198d9e-b3f9-11e6-96a2-e53f3aad1a43.png)

**Comment by PennyQ** [comment]
The solution I could think about is calculating their distance to camera and only mark the shortest distance one as 'selected'. This will add extra coding work (we only use mask array with same data shape) and calculation time, do you have a better solution @astrofrog ? Thanks!

**Comment by astrofrog** [comment]
This has been fixed - we now just pick the true closest one to the click
