### ISSUE TITLE
Scikit-learn package required for k-NN selection on 3D scatter plot

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#232]
@astrofrog Could we add scikit-learn to glue-dependence? Or I could simply add a warning text on command line to remind such a requirement of package.

**Comment by astrofrog** [comment]
The k-NN selection only worked in canvas space so it was essentially equivalent to a circle selection, therefore I've removed it for now (we should add back a proper 3D k-NN or spherical selection in future)
