### ISSUE TITLE
conda install forces downgrade to Qt4

### ISSUE THREAD

**Issue by pllim** [glue-viz/glue-vispy-viewers#234]
On Windows 7 64-bit, using `conda-forge`, typing `conda install glue-vispy-viewers` (Glue is already installed from source) forces downgrade from Qt5 to Qt4. I cancelled it because I don't want the downgrade.

**Comment by astrofrog** [comment]
This is an issue to do with conda-forge - they don't include qt5 and want to pin all packages to qt4. As soon as they allow qt5, I'll update that.
