### ISSUE TITLE
Improve the axis display as how Paraview does

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#30]
![image](https://cloud.githubusercontent.com/assets/13411839/9843835/8f66a53c-5af0-11e5-946d-ba386db43e94.png)
Compared to the current full-size axis that @maxwelltsai and I both prefer this fixed-size axis. It will be located in one corner and keeps the same orientation as the volume object all the time, which could clearly illustrate users how the current status is.

It is not a hard work and I could do it if you also agree with this idea :)

**Comment by astrofrog** [comment]
This would be great!

**Comment by PennyQ** [comment]
Just put the code and instructions from Vispy group here when the version of Vispy in Conda is updated to 0.5 https://github.com/PennyQ/Test/blob/master/volume_test_axis.py
- 1. Make your axis like `XYZAxis(parent=viewbox)` rather than `XYZAxis(parent=viewbox.scene)`. This allows you to define the position of the axis relative to the viewbox's coordinates in the GUI (so it stays fixed to the window instead of the internal scene).
- Connect to the `viewbox.scene.transforms.changed` event and update the orientation of your axes to match. How you do this will depend on the type of camera you are using.
- Make this into a visual of its own and submit a PR  :)

**Comment by PennyQ** [comment]
The axis display works on the development version of Vispy now. Here is the code and PR for this functionality.
https://github.com/vispy/vispy/pull/1125

**Comment by PennyQ** [comment]
I will close this because we already have #76
