### ISSUE TITLE
The instability problem of mouse operations in 'Fly Mode'

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#32]
In the `Fly Mode` the mouse_wheel operation still works but become very slow and sometimes it will give an `IndexError: list index out of range`. So maybe we could just remove the mouse_wheel operation and expect users to use just keyboard to control (actually there is no need for them to use mouse under this mode).

**Comment by astrofrog** [comment]
We have got rid of fly mode, so no longer relevant
