### ISSUE TITLE
Scatter points size not changed when zooming in/out

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#47]
@maxwelltsai  already put this issue on the Vispy Google Group (see the link below) but the reply seems not so helpful.
https://groups.google.com/forum/#!topic/vispy/qHSE-_iOzqI

Maybe it's how the `Markers` visual works. I will put it here for future enhancement if needed.

**Comment by astrofrog** [comment]
This could be an optional feature but the current defaults seem sensible.
