### ISSUE TITLE
'Customised cuts' for 2D image viewer

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue-vispy-viewers#49]
This would be similar to the vertical & horizontal cuts in DS9 (refer link: http://chandra-ed.harvard.edu/learning_ds9part2.html#cuts) to get a 'spectra' with distance and intensity showed. But we also allow users to drag a line as the way they could do to get slices from cubes.

Is it possible to add this functionality for the 2D image viewer in Glue?

**Comment by astrofrog** [comment]
@PennyQ - could you close this issue and open a similar one of the main glue repository, since this is not related to the 3D?

**Comment by PennyQ** [comment]
@astrofrog Done and the new issue is here https://github.com/glue-viz/glue/issues/849
