### ISSUE TITLE
Separate out VisPy/Qt code from Glue code

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#5]
We should try and lay out the code similarly to in the VTK viewer:

https://github.com/astrofrog/cube-viewer/tree/master/cube_viewer

In there, all the Qt/VTK stuff was defined in `vtk_widget.py` and that could be used in any Qt application. Then the `glue_viewer.py` file defined specifically the Glue data viewer. Keeping these nicely separated and the `glue_viewer.py` as simple as possible will make it easier to use the VisPy/Qt code in other projects in future.

**Comment by PennyQ** [comment]
I tried to seperate the Vispy code from the Glue viewer code and make the layout similar to cube-viewer, the key-press functionality is also available now (the code has been committed) :)

**Comment by astrofrog** [comment]
Thanks!
