### ISSUE TITLE
Implement selection toolbar in base data viewer

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#62]
The base `VispyDataViewer` class should include a bare-bones selection toolbar that the scatter and volume rendering viewers can then populate.

**Comment by PennyQ** [comment]
@astrofrog I am working on the toolbar from the PR #88, but the my selection method is based on the transform between the Visual and the View, so could you show me how to get the current Visual such as MultiColorScatter for our scatter plot case, in this PR code?

P.S. Could you also add the `ellipse selection` icon on next pull request? We have rectangle, ellipse, lasso and picking selection, four for now, thanks :)
