### ISSUE TITLE
Implement 3-d lasso selection

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#63]

**Comment by PennyQ** [comment]
@astrofrog Where should I put my script for this issue? I remembered you sent me a sub-repository for storing it but I can't find it now. Can you send it again? Thanks!

**Comment by astrofrog** [comment]
@PennyQ - if the script is already polished, you could put it in a sub-package called `selection` in `glue_vispy_viewers` (even if it's not used by the viewers yet). If you don't want to put it here yet you could put it in https://github.com/glue-viz/glue-3d-selection instead.

**Comment by PennyQ** [comment]
@astrofrog It's in https://github.com/glue-viz/glue-3d-selection now, with free lasso, shape selection and picking functionality. I found I couldn't `push` the script or `merge` it, with permission denied, could you check the setting of that repository?  :)
