### ISSUE TITLE
Add a toolbar button to continuously rotate the 3-d view

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#67]
The views could then continue to rotate while the user is interacting with other viewers.

**Comment by astrofrog** [comment]
@Penny - if you like you could also look into this? Again, this would be something we would do once in `glue_3d_viewers.common` and would apply to all viewers. One idea would be a slider that you can move left or right to make it turn left or right more of less quickly, and continuously.

I'm currently going through issues and trying to divide up work, hence these messages :)

**Comment by PennyQ** [comment]
@astrofrog Yeah, sure. I will take care of it. 
You could just assign some issues that I could help to me and I will let you know if I can't deal with them :)

**Comment by astrofrog** [comment]
Ok, sounds good :)

**Comment by PennyQ** [comment]
@astrofrog I am working on the toolbar from the PR https://github.com/glue-viz/glue-3d-viewer/pull/88, but the my selection method is based on the transform between the `Visual` and the `View`, so could you show me how to get the current `Visual` such as `MultiColorScatter` for our scatter plot case, in this PR code?

**Comment by PennyQ** [comment]
Oh, actually it's not the correct issue, I will move it to #62

**Comment by astrofrog** [comment]
Done by @PennyQ in https://github.com/glue-viz/glue-vispy-viewers/pull/128 - thanks!
