### ISSUE TITLE
Show axis labels in 3-d viewers

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#68]
Can we use `vispy.scene.visuals.Text`? (does it allow 2-d rotation?)

**Comment by PennyQ** [comment]
We could use the 'tick' parameter for `Axis Visual` instead of using `Text Visual` and setting the transform for it.
Here is an example for this:
https://github.com/vispy/vispy/blob/master/examples/basics/scene/surface_plot.py

**Comment by astrofrog** [comment]
@PennyQ - ah yes, good idea. Actually, now you mention it, it would be great to actually show ticks, tick labels, and axis labels (the latter being e.g. 'RA' or 'Mass').

Would you or @maxwelltsai like to work on this?

This should only involve changes in `glue_3d_viewers/common`, and will automatically apply to scatter, volume, and isosurface viewers.

**Comment by PennyQ** [comment]
@astrofrog Yeah, I can do it. So do we still want to make it shown as a 'grid box' way or just a scaled 'xyz' axis? This is the Axis Visual so if we want a grid then we need to use two such visuals and place them to be a grid box I guess.

**Comment by astrofrog** [comment]
@PennyQ - I was thinking we could keep it a grid box, show the ticks on all axes but the labels only on 3 axes - what do you think?

**Comment by PennyQ** [comment]
@astrofrog I found the `AxisVisual` in Vispy [doesn't support 3D now](https://github.com/vispy/vispy/blob/master/vispy/visuals/axis.py) and I asked them about any progress on it, so far no replies. And the method they use is quite hard (from Matplotlib and other research). So do you know any easy methods that we could implement first to make the ticks/labels shown in Glue? Thanks!

**Comment by macrocosme** [comment]
@astrofrog @PennyQ Has there been any progress on this topic?

**Comment by astrofrog** [comment]
@macrocosme - @PennyQ started working on this in https://github.com/glue-viz/glue-vispy-viewers/pull/96 - will try and finish this up this week!

**Comment by astrofrog** [comment]
@macrocosme - this is now done! (in the developer version)
