### ISSUE TITLE
Add support for being able to highlight selections

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#7]
There are two parts to this (separating the VisPy part from the Glue part)
- We need to make sure the VisPy Qt widget can be passed a 3-d mask which indicates a selection, and have the VisPy viewer show that selection.
- We need to update the Glue data viewer part to listen for messages relating to subsets and ask the VisPy Qt widget to show these (I've started to explain this here: http://www.glueviz.org/en/stable/customizing_guide/full_custom_qt_viewer.html#setting-up-a-client).

I can volunteer to help with the second bullet point.

**Comment by PennyQ** [comment]
I would like to help with the first point.

**Comment by astrofrog** [comment]
For the first point, basically I think a good first step would be to add a method to the VisPy widget so that one can do:

```
   my_widget.set_subset(array)
```

where array is a boolean array that indicates which values belong in the subset, and it would show that subset. Then we can easily connect it from the Glue side (which I can do). Does this make sense?

**Comment by PennyQ** [comment]
Yeah, this sounds great. 
Maybe we can first add a simple polygon 3d selection to vispy ( I can do it if needed) and return a subset to glue. Then optimize the selection method with some more advices. 
I cannot find an advanced selection method from the existing examples of Vispy so we might have to be creative on it.

**Comment by astrofrog** [comment]
@PennyQ - I think the 3-d selection will be harder, which is why I was suggesting that first we could just find a way to highlight selections (made in other viewers), but I'll leave it up to you to decide which to do first :)
