### ISSUE TITLE
Add back option to have small 3-d axis in corner

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#76]

**Comment by astrofrog** [comment]
@PennyQ - you worked on this in https://github.com/vispy/vispy/pull/1125, so shall I assign this to you here? This should go in `common/vispy_widget.py` and with an option similar to the one to turn on/off the coordinate grid in `common/viewer_options.py`.

**Comment by PennyQ** [comment]
@astrofrog Ok, I already had one available for the dev Vispy. So we will wait for the new release of Vispy or just implement it?

**Comment by astrofrog** [comment]
@PennyQ - ah, does the code require changes available in dev vispy? If so, it's fine to wait for a new release.

**Comment by PennyQ** [comment]
@astrofrog I tested the code (put here for convenience https://raw.githubusercontent.com/PennyQ/vispy/f3fa22dc87bc2d5c34d1b19c0180bb78781632a4/examples/basics/scene/volume.py) and I found the axis works well for my current version of Vispy (old one) now, so maybe we could implement it into Glue? I could do that if you like :)

**Comment by astrofrog** [comment]
@PennyQ - that would be great!

**Comment by PennyQ** [comment]
See https://github.com/glue-viz/glue-3d-viewer/pull/91
