### ISSUE TITLE
Implement 3-d scatter visualization

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#9]
It would be nice to develop another VisPy viewer, this time for 3-d scatter plots!

**Comment by ChrisBeaumont** [comment]
+1. Also, it might be interesting to explore vispy for 2D scatterplots, especially if we could map components onto point size or color without MPLs massive performance hit

**Comment by maxwelltsai** [comment]
I have some existing code code 3d scatter plots of N-body simulation data. Will integrate it to Glue soon. Could also do a 2D scatter plot (as Chris implies, this would allow us to take the advantage of OpenGL to visual large datasets).

**Comment by PennyQ** [comment]
I am writing to ask if any of you are working on this issue because @maxwelltsai  and I made some progress on the 3D scatter plot with Vispy and we will try to implement it into Glue in the next few days.

**Comment by astrofrog** [comment]
I haven't worked on it, and I'm pretty sure @ChrisBeaumont hasn't either. I think it makes sense to add it to `glue_vispy_viewers/scatter_3d` in this plugin, so feel free to do that!

**Comment by astrofrog** [comment]
Done by @PennyQ :)
