### ISSUE TITLE
Implement volume selection

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#95]
I'll start off by keeping better track of the component IDs in the volume viewer, then @PennyQ can implement the selection

**Comment by PennyQ** [comment]
@astrofrog I am trying to implement dendrogram selection for 3D volume and now I could get the array index of the max value along the eye sight when click the mouse, is it possible to get the dendrogram structure depends on a 3D index as what 2D image did `structure = self.dendrogram.structure_at(indices)`, and get this structure highlighted? Thanks :)

**Comment by astrofrog** [comment]
This is now working correctly :)
