### ISSUE TITLE
Saving images and movies from 3D viewers

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-vispy-viewers#99]
It would be nice to add a save button to the toolbar.

@PennyQ - if you like, you could look into how one can programmatically get the buffer from VisPy and save it to a file? Then adding a toolbar icon should be easy.

(Let's not worry about movies initially)

**Comment by PennyQ** [comment]
@astrofrog The 2D image output could be solved through the `canvas.render()` as shown [here](https://github.com/vispy/vispy/blob/master/vispy/scene/canvas.py) 

An easy example would be:
`from vispy import io`
`img = canvas.render() # canvas = scene.SceneCanvas(keys='interactive', bgcolor='w')`
`io.write_png('output.png', img)`

**Comment by astrofrog** [comment]
Ok cool :) Do you want to try and add a floppy disk icon (which exists in the set of glue icons) to the toolbar? I can provide guidance if needed!

**Comment by PennyQ** [comment]
Add icon instruction at #123

**Comment by astrofrog** [comment]
This was done by @PennyQ a little while back!
